SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY,
    COUNT(*) AS PROCUTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY,
    COUNT(*) AS PROCUTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;