SELECT YEAR(ONLINE.SALES_DATE) AS YEAR,
    MONTH(ONLINE.SALES_DATE) AS MONTH,
    USER.GENDER,
    COUNT(DISTINCT(ONLINE.USER_ID)) AS USERS
FROM USER_INFO AS USER JOIN ONLINE_SALE AS ONLINE
ON USER.USER_ID = ONLINE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;