SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES AS A JOIN
    (SELECT HOST_ID
     FROM PLACES
     GROUP BY HOST_ID
     HAVING COUNT(HOST_ID) > 1
    ) AS B
ON A.HOST_ID = B.HOST_ID
ORDER BY A.ID;

SELECT *
FROM PLACES
WHERE HOST_ID IN
    (SELECT HOST_ID
     FROM PLACES
     GROUP BY HOST_ID
     HAVING COUNT(HOST_ID) > 1
    )
ORDER BY ID;