SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P JOIN
    (SELECT A.MEMBER_ID, A.REVIEW_TEXT, A.REVIEW_DATE
    FROM REST_REVIEW AS A JOIN
        (SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY REVIEW_CNT DESC
         LIMIT 1
        ) AS B
     ON A.MEMBER_ID = B.MEMBER_ID
    ) AS R
ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P JOIN REST_REVIEW AS R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
                     GROUP BY MEMBER_ID
                    ORDER BY COUNT(MEMBER_ID) DESC
                    LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT