-- IF
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE TLNO LIKE '031%'
ORDER BY WAREHOUSE_ID;

-- IFNULL
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE TLNO LIKE '031%'
ORDER BY WAREHOUSE_ID;

-- CASE
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    CASE
        WHEN FREEZER_YN IS NULL THEN 'N'
        ELSE FREEZER_YN
    END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE TLNO LIKE '031%'
ORDER BY WAREHOUSE_ID;